require('./docker_start');
require('./create-test-db');
require('./regbot-tests');
require('./regbot-unit-test');
require('./sip-register-tests');
require('./sip-options-tests');
require('./cli-tests');
require('./docker_stop');
require('./utils');
